CREATE TABLE CAMERE (
  ID_Camera INT NOT NULL,
  NumarCamera VARCHAR2(10) NOT NULL,
  Tip VARCHAR2(50) NOT NULL,
  PretNoapte DECIMAL(10, 2) NOT NULL,
  Etaj NUMBER,
  Capacitate INT,
  CONSTRAINT CAMERE_ID_PK PRIMARY KEY (ID_Camera),
  CONSTRAINT CAMERE_NUMAR_UK UNIQUE (NumarCamera)
);
CREATE INDEX CAMERE_NUMAR_IX ON CAMERE (NUMARCAMERA);
CREATE INDEX CAMERE_TIP_IX ON CAMERE (TIP);

CREATE TABLE CLIENTI (
  ID_Client INT NOT NULL,
  Nume VARCHAR2(255),
  Prenume VARCHAR2(255),
  Email VARCHAR2(255),
  Telefon VARCHAR2(20),
  CONSTRAINT CLIENTI_ID_PK PRIMARY KEY (ID_Client),
  CONSTRAINT CLIENTI_EMAIL_UK UNIQUE (Email),
  CONSTRAINT CLIENTI_NUME_NN CHECK (Nume IS NOT NULL),
  CONSTRAINT CLIENTI_PRENUME_NN CHECK (Prenume IS NOT NULL)
);
CREATE INDEX CLIENTI_NUME_IX ON CLIENTI (NUME);
CREATE INDEX CLIENTI_PRENUME_IX ON CLIENTI (PRENUME);
CREATE INDEX CLIENTI_EMAIL_IX ON CLIENTI (EMAIL);

CREATE TABLE REZERVARI (
  ID_Rezervare INT NOT NULL,
  ID_Client INT NOT NULL,
  ID_Camera INT NOT NULL,
  DataInceput DATE NOT NULL,
  DataSfarsit DATE NOT NULL,
  Status VARCHAR2(50),
  CONSTRAINT REZERVARI_CLIENT_FK FOREIGN KEY (ID_Client) REFERENCES CLIENTI(ID_Client),
  CONSTRAINT REZERVARI_CAMERA_FK FOREIGN KEY (ID_Camera) REFERENCES CAMERE(ID_Camera)
);

CREATE TABLE PLATI (
  ID_Plata INT NOT NULL,
  ID_Rezervare INT NOT NULL,
  Suma DECIMAL(10, 2) NOT NULL,
  DataPlata DATE NOT NULL,
  Modalitate VARCHAR2(50),
  CONSTRAINT PLATI_ID_PK PRIMARY KEY (ID_Plata),
  CONSTRAINT PLATI_REZERVARE_FK FOREIGN KEY (ID_Rezervare) REFERENCES REZERVARI(ID_Rezervare)
);

CREATE TABLE SERVICII_EXTRA (
  ID_Serviciu INT NOT NULL,
  Denumire VARCHAR2(255) NOT NULL,
  Pret DECIMAL(10, 2) NOT NULL,
  Descriere VARCHAR2(1000),
  CONSTRAINT SERVICII_EXTRA_PK PRIMARY KEY (ID_Serviciu),
  CONSTRAINT SERVICII_EXTRA_DENUMIRE_UK UNIQUE (Denumire)
);

CREATE TABLE REZERVARI_SERVICII_EXTRA (
  ID_Rezervare_Serviciu INT PRIMARY KEY,
  ID_Rezervare INT NOT NULL,
  ID_Serviciu INT NOT NULL,
  DataRezervare DATE NOT NULL,
  CONSTRAINT FK_Rezervari_Servicii_Reservation FOREIGN KEY (ID_Rezervare) REFERENCES REZERVARI(ID_Rezervare),
  CONSTRAINT FK_Rezervari_Servicii_Extra FOREIGN KEY (ID_Serviciu) REFERENCES SERVICII_EXTRA(ID_Serviciu)
);
